#![allow(warnings)]

#![feature(fn_traits)]
#![feature(thread_local)]
#![feature(tuple_trait)]
#![feature(unboxed_closures)]

use egui::*;
use egui::color_picker::*;
use egui::ecolor::*;
use egui::emath::*;
use egui::emath::align::*;
use egui::emath::easing::*;
use egui::emath::smart_aim::*;
use egui::epaint::*;
use egui::epaint::tessellator::*;
use egui::epaint::text::*;
use egui::epaint::text::cursor::*;
use egui::Id;
use egui::collapsing_header::*;
use egui::containers::*;
use egui::containers::menu::*;
use egui::containers::menu::SubMenu;
use egui::gui_zoom::*;
use egui::introspection::*;
use egui::layers::*;
use egui::load::*;
use egui::os::*;
use egui::output::*;
use egui::panel::*;
use egui::scroll_area::*;
use egui::style::*;
use egui::text::*;
use egui::text_edit::*;
use egui::text_selection::*;
use egui::text_selection::text_cursor_state::*;
use egui::text_selection::visuals::*;
use egui::util::undoer::*;
use serde::*;
use serde::de::*;
use std::borrow::*;
use std::collections::*;
use std::ffi::*;
use std::marker::PhantomData;
use std::marker::Tuple;
use std::mem::*;
use std::ops::*;
use std::sync::atomic::AtomicUsize;
use std::time::*;
use std::panic;
use std::panic::catch_unwind;
use std::sync::*;

include!(concat!(env!("CARGO_MANIFEST_DIR"), "/../target/bindings/egui_fn.rs"));

/// A registry containing all `egui` functions callable from C#.
const EGUI_FNS: EguiFnMap = AUTOGENERATED_EGUI_FNS
    // Bindings for AreaState
    .with(EguiFn::egui_containers_area_AreaState_load, |ctx: EguiPointer<Context>, id: Id| unsafe { AreaState::load(ctx.get(), id) })
    // Bindings for CentralPanel
    .with(EguiFn::egui_containers_panel_CentralPanel_show, |ctx: EguiPointer<Context>, panel: CentralPanel, callback: EguiCallback| unsafe {
        panel.show(ctx.get(), |ui| {
            callback.invoke(ui as *const _ as *const _);
        }).response
    })
    .with(EguiFn::egui_containers_panel_CentralPanel_show_inside, |mut ui: EguiPointer<Ui>, panel: CentralPanel, callback: EguiCallback| unsafe {
        panel.show_inside(ui.get_mut(), |ui| {
            callback.invoke(ui as *const _ as *const _);
        }).response
    })
    // Bindings for Context
    .with(EguiFn::egui_context_Context_default, || EguiHandle::to_heap(Context::default()))
    .with(EguiFn::egui_context_Context_ref_id, |ctx: EguiPointer<Context>| unsafe { *transmute::<_, &usize>(ctx.get()) })
    .with(EguiFn::egui_context_Context_ref_count, |ctx: EguiPointer<Context>| unsafe { transmute::<_, &&AtomicUsize>(ctx.get()).load(atomic::Ordering::SeqCst) })
    .with(EguiFn::egui_context_Context_ref_decrement, |ctx: EguiPointer<Context>| unsafe { (ctx.get() as *const Context).read(); })
    .with(EguiFn::egui_context_Context_request_discard, |ctx: EguiPointer<Context>, x: String| unsafe { ctx.get().request_discard(x) })
    .with(EguiFn::egui_context_Context_layer_painter, |ctx: EguiPointer<Context>, layer_id: LayerId| unsafe { EguiHandle::to_heap(ctx.get().layer_painter(layer_id)) })
    .with(EguiFn::egui_context_Context_debug_painter, |ctx: EguiPointer<Context>| unsafe { EguiHandle::to_heap(ctx.get().debug_painter()) })
    .with(EguiFn::egui_context_Context_run, |ctx: EguiPointer<Context>, raw_input: RawInput, callback: EguiCallback| unsafe {
        ctx.get().run(raw_input, |ctx| {
            callback.invoke(std::ptr::null());
        })
    })
    // Bindings for Grid
    .with(EguiFn::egui_grid_Grid_show, |mut ui: EguiPointer<Ui>, grid: Grid, callback: EguiCallback| unsafe {
        grid.show(ui.get_mut(), |ui| {
            callback.invoke(ui as *const _ as *const _);
        }).response
    })
    // Bindings for Id
    .with(EguiFn::egui_id_Id_new, |source: String| Id::new(source))
    .with(EguiFn::egui_id_Id_with, |this: Id, child: String| this.with(child))
    // Bindings for Popup
    .with(EguiFn::egui_containers_popup_Popup_close_all, |ctx: EguiPointer<Context>| unsafe { Popup::close_all(ctx.get()) })
    .with(EguiFn::egui_containers_popup_Popup_close_id, |ctx: EguiPointer<Context>, id: Id| unsafe { Popup::close_id(ctx.get(), id) })
    .with(EguiFn::egui_containers_popup_Popup_open_id, |ctx: EguiPointer<Context>, id: Id| unsafe { Popup::open_id(ctx.get(), id) })
    .with(EguiFn::egui_containers_popup_Popup_toggle_id, |ctx: EguiPointer<Context>, id: Id| unsafe { Popup::toggle_id(ctx.get(), id) })
    .with(EguiFn::egui_containers_popup_Popup_is_any_open, |ctx: EguiPointer<Context>| unsafe { Popup::is_any_open(ctx.get()) })
    .with(EguiFn::egui_containers_popup_Popup_is_id_open, |ctx: EguiPointer<Context>, id: Id| unsafe { Popup::is_id_open(ctx.get(), id) })
    .with(EguiFn::egui_containers_popup_Popup_position_of_id, |ctx: EguiPointer<Context>, id: Id| unsafe { Popup::position_of_id(ctx.get(), id) })
    .with(EguiFn::egui_containers_popup_Popup_show, |ctx: EguiPointer<Context>, popup: SerializablePopup, mut is_open: bool, callback: EguiCallback| unsafe {
        let response = popup.to_popup(ctx.get(), &mut is_open).show(|ui| callback.invoke(ui as *const _ as *const _));
        (response.map(|x| x.response), is_open)
    })
    // Bindings for RawInput
    .with(EguiFn::egui_data_input_RawInput_append, |mut this: RawInput, newer: RawInput| {
        this.append(newer);
        this
    })
    .with(EguiFn::egui_data_input_RawInput_take, |mut this: RawInput| {
        let new = this.take();
        (this, new)
    })
    .with(EguiFn::egui_data_input_RawInput_viewport, |this: RawInput| this.viewport().clone())
    // Bindings for Rect
    .with(EguiFn::emath_rect_Rect_center, |r: Rect| r.center())
    .with(EguiFn::emath_rect_Rect_set_center, |mut r: Rect, p: Pos2| { r.set_center(p); r })
    .with(EguiFn::emath_rect_Rect_extend_with, |mut r: Rect, p: Pos2| { r.extend_with(p); r })
    .with(EguiFn::emath_rect_Rect_extend_with, |mut r: Rect, p: Pos2| { r.extend_with(p); r })
    .with(EguiFn::emath_rect_Rect_extend_with_x, |mut r: Rect, p: f32| { r.extend_with_x(p); r })
    .with(EguiFn::emath_rect_Rect_extend_with_y, |mut r: Rect, p: f32| { r.extend_with_y(p); r })
    // Bindings for RectAlign
    .with(EguiFn::emath_rect_align_RectAlign_find_best_align, |values_to_try: Vec<RectAlign>, screen_rect: Rect, parent_rect: Rect, gap: f32, expected_size: Vec2| RectAlign::find_best_align(values_to_try.into_iter(), screen_rect, parent_rect, gap, expected_size))
    // Bindings for Response
    .with(EguiFn::egui_response_Response_mark_changed, |mut x: Response| { x.mark_changed(); x })
    .with(EguiFn::egui_response_Response_mark_changed, |mut x: Response| { x.set_close(); x })
    // Bindings for Sense
    .with(EguiFn::egui_sense_Sense_interactive, |x: u8| Sense::from_bits_truncate(x).interactive())
    .with(EguiFn::egui_sense_Sense_senses_click, |x: u8| Sense::from_bits_truncate(x).senses_click())
    .with(EguiFn::egui_sense_Sense_senses_drag, |x: u8| Sense::from_bits_truncate(x).senses_drag())
    .with(EguiFn::egui_sense_Sense_is_focusable, |x: u8| Sense::from_bits_truncate(x).is_focusable())
    // Bindings for Ui
    .with(EguiFn::egui_ui_Ui_allocate_painter, |mut ui: EguiPointer<Ui>, desired_size: Vec2, sense: Sense| unsafe {
        let (response, painter) = ui.get_mut().allocate_painter(desired_size, sense);
        (response, EguiHandle::to_heap(painter))
    })
    .with(EguiFn::egui_ui_Ui_painter, |ui: EguiPointer<Ui>| unsafe { EguiHandle::to_heap(ui.get().painter().clone()) })
    .with(EguiFn::egui_ui_Ui_painter, |ui: EguiPointer<Ui>, rect: Rect| unsafe { EguiHandle::to_heap(ui.get().painter_at(rect)) })
    .with(EguiFn::egui_ui_Ui_spacing, |ui: EguiPointer<Ui>| unsafe { ui.get().spacing().clone() })
    .with(EguiFn::egui_ui_Ui_style, |ui: EguiPointer<Ui>| unsafe { ui.get().style().clone() })
    .with(EguiFn::egui_ui_Ui_layout, |ui: EguiPointer<Ui>| unsafe { ui.get().layout().clone() })
    .with(EguiFn::egui_ui_Ui_visuals, |ui: EguiPointer<Ui>| unsafe { ui.get().visuals().clone() })
    .with(EguiFn::egui_ui_Ui_stack, |ui: EguiPointer<Ui>| unsafe { ui.get().stack().clone() })
    .with(EguiFn::egui_ui_Ui_separator, |mut ui: EguiPointer<Ui>| unsafe { ui.get_mut().separator() })
    // Bindings for WidgetText
    .with(EguiFn::egui_widget_text_WidgetText_text, |x: WidgetText| x.text().to_string())
    // Bindings for Window
    .with(EguiFn::egui_containers_window_Window_show, |ctx: EguiPointer<Context>, window: SerializableWindow, open: Option<bool>, add_contents: EguiCallback| unsafe {
        let window = Window::from(window);
        if let Some(mut is_open) = open {
            let response = window.open(&mut is_open).show(ctx.get(), |ui| add_contents.invoke(ui as *const _ as *const _));
            (response.map(|x| x.response), is_open)
        }
        else {
            let response = window.show(ctx.get(), |ui| add_contents.invoke(ui as *const _ as *const _));
            (response.map(|x| x.response), true)
        }
    })
    // Miscellaneous
    .with(EguiFn::emath_format_with_decimals_in_range, format_with_decimals_in_range as fn(f64, RangeInclusive<usize>) -> _);

/// A C# callback for `egui` to invoke.
#[derive(Copy, Clone)]
#[repr(C)]
pub struct EguiCallback {
    /// The function to call.
    func: unsafe extern "C" fn(*const c_void, *const c_void),
    /// Data to pass as the second function argument.
    data: *const c_void
}

impl EguiCallback {
    /// Invokes the callback.
    /// 
    /// # Safety
    /// 
    /// All invariants for [`Self::func`] must be satisfied.
    pub unsafe fn invoke(&self, argument: *const c_void) {
        (self.func)(argument, self.data)
    }
}

impl Serialize for EguiCallback {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
        where
            S: Serializer {
        [self.func as usize, self.data as usize].serialize(serializer)
    }
}

impl<'a> Deserialize<'a> for EguiCallback {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
        where
            D: Deserializer<'a> {
        unsafe {
            let [func, data] = <[usize; 2] as Deserialize<'a>>::deserialize(deserializer)?;
            Ok(Self {
                func: transmute(func),
                data: data as *const _
            })
        }
    }
}

/// An `egui` object that is passed by reference.
#[derive(Copy, Clone, Serialize, Deserialize)]
#[repr(C)]
pub struct EguiPointer<T> {
    /// The underlying pointer.
    ptr: usize,
    /// Marker data identifying the type.
    marker: PhantomData<*mut T>
}

impl<T> EguiPointer<T> {
    /// Gets a reference to the underlying object.
    /// 
    /// # Safety
    /// 
    /// The pointer must be valid, and no mutable references may exist to it.
    pub unsafe fn get(&self) -> &T {
        assert_ne!(self.ptr, 0, "egui object was not initialized");
        &*(self.ptr as *const _)
    }

    /// Gets a mutable reference to the underlying object.
    /// 
    /// # Safety
    /// 
    /// The pointer must be valid, and no other references may exist to it.
    pub unsafe fn get_mut(&mut self) -> &mut T {
        assert_ne!(self.ptr, 0, "egui object was not initialized");
        &mut *(self.ptr as *mut _)
    }
}

/// Represents a heap-allocated `egui` object.
#[derive(Copy, Clone, Serialize, Deserialize)]
#[repr(C)]
pub struct EguiHandle {
    /// A pointer to the object.
    ptr: usize,
    /// Metadata about the pointer used for internal purposes.
    metadata: usize
}

impl EguiHandle {
    /// Allocates `value` on the heap and returns a handle to it.
    pub fn to_heap<T: 'static>(value: T) -> Self {
        let ptr = Box::into_raw(Box::new(value)) as usize;
        let metadata = std::ptr::drop_in_place::<T> as usize;
        Self {
            ptr,
            metadata
        }
    }
}

/// Describes the result of an `egui` call.
#[derive(Copy, Clone)]
#[repr(C)]
pub struct EguiInvokeResult {
    /// Whether `return_value` holds a serialized value or an error string.
    pub success: bool,
    /// If [`Self::success`], then the serialized data that the function returned.
    /// Otherwise, holds a UTF8 string describing what went wrong.
    pub return_value: EguiSliceU8
}

/// Describes a section of a `u8` array.
#[derive(Copy, Clone)]
#[repr(C)]
pub struct EguiSliceU8 {
    /// A pointer to the data buffer.
    pub ptr: *const u8,
    /// The length of the data in bytes.
    pub len: usize
}

impl EguiSliceU8 {
    /// Converts `x` to an FFI-compatible slice.
    /// 
    /// # Safety
    /// 
    /// The lifetime of the returned slice should not outlive `x`. 
    pub const fn from_slice(x: &[u8]) -> Self {
        Self {
            ptr: x.as_ptr(),
            len: x.len()
        }
    }

    /// Converts this object to a Rust slice pointer.
    /// 
    /// # Safety
    /// 
    /// For this function call to be sound, `self` must refer
    /// to a valid array of `u8` with at least [`Self::len`] elements.
    pub unsafe fn to_ptr(&self) -> *const [u8] {
        if self.len == 0 {
            &[]
        }
        else {
            std::slice::from_raw_parts(self.ptr, self.len)
        }
    }

    /// Converts this object to a Rust slice.
    /// 
    /// # Safety
    /// 
    /// For this function call to be sound, `self` must refer
    /// to a valid array of `u8` with at least [`Self::len`] elements.
    pub unsafe fn to_slice(&self) -> &[u8] {
        if self.len == 0 {
            &[]
        }
        else {
            std::slice::from_raw_parts(self.ptr, self.len)
        }
    }
}

/// Initializes the `egui` bindings library.
#[no_mangle]
pub unsafe extern "C" fn egui_init() {
    //panic::set_hook(Box::new(|_| ()));
}

#[no_mangle]
pub unsafe extern "C" fn egui_invoke(f: EguiFn, args: EguiSliceU8) -> EguiInvokeResult {
    /// The serialization buffer to which results will be written.
    #[thread_local]
    static mut RETURN_BUFFER: Vec<u8> = Vec::new();

    match catch_unwind(|| {
        if let Some(invoker) = EGUI_FNS.inner[f as usize] {
            invoker.invoke(args.to_ptr(), std::ptr::addr_of_mut!(RETURN_BUFFER));
            EguiInvokeResult {
                success: true,
                return_value: EguiSliceU8::from_slice(&*std::ptr::addr_of_mut!(RETURN_BUFFER))
            }
        }
        else {
            panic!("Function {f:?} not implemented")
        }
    }) {
        Ok(x) => x,
        Err(error) => {
            let error_message = error.downcast_ref::<&'static str>()
                .map(|x| x.to_string())
                .unwrap_or_else(|| error.downcast_ref::<String>().cloned().unwrap_or_default());
            
            let return_buffer = &mut *std::ptr::addr_of_mut!(RETURN_BUFFER);
            return_buffer.clear();
            for character in error_message.encode_utf16() {
                return_buffer.extend(character.to_ne_bytes());
            }

            EguiInvokeResult {
                success: false,
                return_value: EguiSliceU8::from_slice(&return_buffer)
            }
        }
    }
}

/// Frees an `egui` object from the heap.
#[no_mangle]
pub unsafe extern "C" fn egui_drop(handle: EguiHandle) {
    transmute::<_, unsafe fn(usize)>(handle.metadata)(handle.ptr)
}

/// Holds bindings for all `egui` functions and allows for translating from [`EguiFn`] names to function pointers.
struct EguiFnMap {
    /// A mapping from [`EguiFn`] bindings to the underlying function to invoke.
    inner: [Option<EguiFnInvoker>; EguiFn::ALL.len()]
}

impl EguiFnMap {
    /// Adds a function (that has call-by-value semantics) and returns the new map.
    pub const fn with<A: DeserializeOwned + Tuple, R: Serialize>(mut self, binding: EguiFn, f: impl Copy + Fn<A, Output = R>) -> Self {
        self.inner[binding as usize] = Some(EguiFnInvoker::new(f));
        self
    }
}

/// Creates a new, empty function map.
const fn egui_fn_map() -> EguiFnMap {
    EguiFnMap {
        inner: [None; EguiFn::ALL.len()]
    }
}

/// A type-erased `egui` function that may be called with serialized arguments/result.
#[derive(Copy, Clone, Debug)]
struct EguiFnInvoker {
    /// The `fn` object to pass to `func`.
    data: *const (),
    /// The [`EguiFnInvokable::invoke`] method to call.
    func: unsafe fn(*const (), *const [u8], *mut Vec<u8>)
}

impl EguiFnInvoker {
    /// Stores the provided [`EguiFnInvokable`] on the stack for later use.
    /// `F` should be a `fn` pointer.
    pub const fn new<A: DeserializeOwned + Tuple, F: Copy + Fn<A, Output: Serialize>>(f: F) -> Self {
        unsafe {
            /// Allows for safely reading the data of `f`.
            #[repr(C)]
            struct PaddedPtr<F> {
                /// The function being called.
                pub f: F,
                /// Padding for when `F` is less than the size of a pointer.
                pub padding: *const ()
            }

            if size_of::<*const ()>() < size_of::<F>() || align_of::<*const ()>() < align_of::<F>() {
                panic!("Invokable function must be thin pointer");
            }

            let padded = PaddedPtr { f, padding: std::ptr::null() };

            Self {
                data: std::ptr::read(&padded as *const _ as *const _),
                func: transmute(Self::call_fn::<A, F> as unsafe fn(_, _, _))
            }
        }
    }

    /// Invokes the underlying function.
    /// 
    /// # Safety
    /// 
    /// For this function call to be sound, `ptr` must refer to a valid instance
    /// of the invoker function's type. 
    pub unsafe fn invoke(&self, args: *const [u8], ret: *mut Vec<u8>) {
        (self.func)(&self.data as *const _ as *const _, args, ret)
    }

    /// Invokes the underlying function.
    /// 
    /// # Safety
    /// 
    /// For this function call to be sound, `ptr` must refer to a valid instance
    /// of the invoker function's type. 
    unsafe fn call_fn<A: DeserializeOwned + Tuple, F: Copy + Fn<A, Output: Serialize>>(f: &F, args: *const [u8], ret: *mut Vec<u8>) {
        let deserialized_args = bincode::deserialize(&*args).expect("Failed to decode args");
        let result = f.call(deserialized_args);
        (*ret).clear();
        bincode::serialize_into(&mut *ret, &result).expect("Failed to encode result");
    }
}

/// Helper struct for serializing popups
#[derive(Clone, Serialize, Deserialize)]
struct SerializablePopup {
    pub id: Id,
    pub anchor: PopupAnchor,
    pub rect_align: RectAlign,
    pub alternative_aligns: Option<Vec<RectAlign>>,
    pub layer_id: LayerId,
    pub open_kind: u8,
    pub open_command: Option<SetOpenCommand>,
    pub close_behavior: PopupCloseBehavior,
    pub info: Option<UiStackInfo>,
    pub kind: PopupKind,
    pub gap: f32,
    pub widget_clicked_elsewhere: bool,
    pub width: Option<f32>,
    pub sense: Sense,
    pub layout: Layout,
    pub frame: Option<Frame>,
    pub style: Option<Style>,
    pub menu_style: bool
}

impl SerializablePopup {
    pub fn to_popup<'a>(&'a self, ctx: &Context, open_bool: &'a mut bool) -> Popup<'a> {
        Popup {
            id: self.id,
            open_kind: match self.open_kind {
                0 => OpenKind::Open,
                1 => OpenKind::Closed,
                2 => OpenKind::Bool(open_bool),
                3 => OpenKind::Memory { set: self.open_command.clone() },
                _ => panic!("Invalid open kind value")
            },
            ctx: ctx.clone(),
            anchor: self.anchor,
            rect_align: self.rect_align,
            alternative_aligns: self.alternative_aligns.as_deref(),
            layer_id: self.layer_id,
            close_behavior: self.close_behavior,
            info: self.info.clone(),
            kind: self.kind,
            gap: self.gap,
            widget_clicked_elsewhere: self.widget_clicked_elsewhere,
            width: self.width,
            sense: self.sense,
            layout: self.layout,
            frame: self.frame,
            style: if self.menu_style {
                StyleModifier::from(menu_style)
            } else if let Some(style) = &self.style {
                style.clone().into()
            }
            else {
                StyleModifier::default()
            },
        }
    }
}

/// Helper struct for serializing windows
#[derive(Clone, Serialize, Deserialize)]
struct SerializableWindow {
    title: WidgetText,
    area: Area,
    frame: Option<Frame>,
    resize: Resize,
    scroll: ScrollArea,
    collapsible: bool,
    default_open: bool,
    with_title_bar: bool,
    fade_out: bool,
}

impl<'a> From<SerializableWindow> for Window<'a> {
    fn from(value: SerializableWindow) -> Self {
        Window {
            title: value.title,
            open: None,
            area: value.area,
            frame: value.frame,
            resize: value.resize,
            scroll: value.scroll,
            collapsible: value.collapsible,
            default_open: value.default_open,
            with_title_bar: value.with_title_bar,
            fade_out: value.fade_out
        }
    }
}

/// Functions that can be run as tests.
#[cfg(test)]
mod tests {
    use super::*;
    
    /// Creates a list of all unbound methods and stubs for them. 
    #[test]
    fn report_unbound_methods() {
        let mut result = String::new();
        let mut bound = 0;

        for func in EguiFn::ALL {
            if EGUI_FNS.inner[*func as usize].is_none() {
                result += &format!("{func:?}\n");
            }
            else {
                bound += 1;
            }
        }
        
        result = format!("{bound} / {} ({}%) bound\n{result}", EguiFn::ALL.len(), (100.0 * bound as f32 / EguiFn::ALL.len() as f32).floor());
        std::fs::write("progress_report.txt", result).expect("Failed to write progress report");
    }
}